### ISSUE TITLE
Naming scheme

### ISSUE THREAD

**Issue by sfilippone** [sourceryinstitute/smart-pointers#5]
It would probably be a good idea to add a unique prefix (something like  "xyz_") to the visible entity names for this library, so as to make integration into other codes  easier and/or more consistent with existing practices.

**Comment by rouson** [comment]
@sfilippone this issue is fixed in commit 826c0472e4c2ab9063a086252a1b04894f0790e3.  I decided to prepend `ref_` the names of all modules, submodules, and derived types.  This choice has the nice consequence that the type previously named `counter_t` is now named `ref_counter_t`.  I hope this prefix meets your needs/desires for use in PSBLAS.
